# Generated by Django 5.2.13 on 2026-04-22 10:01

import core.models
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name="Scrape",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.models.make_object_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(unique=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Website",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.models.make_object_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("url", models.URLField()),
                ("content", models.TextField()),
                ("images", models.JSONField(blank=True, default=list)),
                (
                    "content_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "indexed_with_model",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scrape",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="scrapes.scrape"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.models.make_object_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("chunk_index", models.PositiveIntegerField()),
                ("text", models.TextField()),
                ("token_count", models.PositiveIntegerField()),
                ("heading_path", models.JSONField(blank=True, default=list)),
                ("embedding_model", models.CharField(max_length=64)),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunk_set",
                        to="scrapes.website",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="scrape",
            index=models.Index(
                fields=["created_on"], name="scrapes_scr_created_51e5b6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="website",
            unique_together={("url", "scrape")},
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=models.Index(
                fields=["embedding_model"], name="scrapes_chu_embeddi_fd43e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="chunk_embedding_hnsw",
                opclasses=["vector_cosine_ops"],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chunk",
            unique_together={("website", "chunk_index")},
        ),
    ]
