# Generated by Django 5.2.11 on 2026-02-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrapes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="images",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
