# Generated by Django 5.2.13 on 2026-04-22 11:10

import core.models
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrapes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RAGQueryLog",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.models.make_object_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("query", models.TextField()),
                ("answer", models.TextField(blank=True, default="")),
                ("scrape_id", models.CharField(blank=True, default="", max_length=64)),
                ("top_similarity", models.FloatField(blank=True, null=True)),
                ("below_threshold", models.BooleanField(default=False)),
                ("invalid_citations", models.JSONField(blank=True, default=list)),
                ("sources", models.JSONField(blank=True, default=list)),
                ("model", models.CharField(blank=True, default="", max_length=64)),
                ("prompt_tokens", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "completion_tokens",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("total_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("retrieval_ms", models.FloatField(blank=True, null=True)),
                ("generation_ms", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="chunk",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="chunk_search_gin"
            ),
        ),
        migrations.AddField(
            model_name="ragquerylog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="ragquerylog",
            index=models.Index(
                fields=["created_on"], name="scrapes_rag_created_b1436a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ragquerylog",
            index=models.Index(
                fields=["below_threshold"], name="scrapes_rag_below_t_55f80c_idx"
            ),
        ),
    ]
