# Generated by Django 5.2.11 on 2026-02-23 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scrapes", "0002_website_images"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="website",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="website",
            name="scrapes_web_created_db39a0_idx",
        ),
        migrations.AlterUniqueTogether(
            name="website",
            unique_together={("url", "scrape")},
        ),
    ]
