# Generated by Django 5.2.12 on 2026-03-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0003_alter_website_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrape',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
