# Generated by Django 5.2.12 on 2026-03-27 02:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrapes", "0004_alter_scrape_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="chunks",
            field=models.JSONField(
                blank=True, default=list, help_text="Text chunks for RAG"
            ),
        ),
        migrations.AddField(
            model_name="website",
            name="embeddings",
            field=models.JSONField(
                blank=True, default=list, help_text="Embeddings for each chunk"
            ),
        ),
        migrations.AddField(
            model_name="website",
            name="is_indexed",
            field=models.BooleanField(
                default=False, help_text="Whether content has been indexed for RAG"
            ),
        ),
        migrations.AddIndex(
            model_name="website",
            index=models.Index(
                fields=["is_indexed"], name="scrapes_web_is_inde_0b1ac2_idx"
            ),
        ),
    ]
